Capistrano::Configuration.instance( :must_exist ).load do
  namespace :sass do
    desc 'Updates the stylesheets generated by Sass'
    task :update, :roles => :app do
      invoke_command "cd #{latest_release}; rake app:sass:update RAILS_ENV=#{rails_env}"
    end
  end
end